export { default as api } from './api'
export * from './auth'
export * from './products'
export * from './cart'
export * from './orders'
export * from './merchants'
export * from './payments'
export * from './chat'
export * from './addresses'
export * from './reviews'
export * from './notifications'
export * from './wishlist'
export * from './price-alerts'
export * from './stock-notifications'
export * from './gift-registry'
export * from './referral'
export * from './bulk-ordering'
export * from './inventory'
export * from './upload'

// Export API instances for hooks
export { merchantsService as merchantsApi } from './merchants'
export { notificationsService as notificationsApi } from './notifications'
